/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package osm.archive.stat;

import lombok.extern.log4j.Log4j2;
import org.apache.commons.compress.compressors.CompressorException;
import org.apache.commons.compress.compressors.CompressorStreamFactory;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import osm.archive.stat.node.Node;
import osm.archive.stat.node.NodeReader;
import osm.archive.stat.node.XmlNodeReader;
import osm.archive.stat.statistics.OsmStatistics;
import osm.archive.stat.statistics.Statistics;

import javax.xml.stream.XMLStreamException;
import java.io.*;
import java.nio.file.Files;
import java.nio.file.Path;

public class App {

    private static final Logger log
            = LoggerFactory.getLogger(App.class);

    public static void main(String[] args) throws Exception {

        CliParser parser = new CliParser();
        AppConfiguration configuration = parser.parse(args);
        if (configuration == null) {
            parser.printHelp();
            return;
        }

        Path inputPath = Path.of(configuration.path());
        InputStream inputStream = new BufferedInputStream(Files.newInputStream(inputPath));

        if (configuration.isArchive()) {
            try {
                inputStream =
                        new CompressorStreamFactory().createCompressorInputStream(inputStream);
            } catch (CompressorException e) {
                log.error("Can not create compress stream", e);
                System.out.println("Can not read archive");
                return;
            }
        }

        try {
            NodeReader nodeReader = new XmlNodeReader(inputStream);
            Statistics<Node> osmStatistic = new OsmStatistics();
            while (nodeReader.hasNext()) {
                osmStatistic.add(nodeReader.read());
            }
            log.info(osmStatistic.toString());
        } catch (XMLStreamException e) {
            log.error("Can not create xml reader", e);
            System.out.println("Can not parse xml");
        } catch (Exception e) {
            e.printStackTrace();
        }


    }
}
