//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.07 at 05:40:18 AM UTC 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ccfit.nsu.ru/schema/crack-hash-response")
package ru.nsu.ccfit.schema.crack_hash_response;
